### ISSUE TITLE
What's different between the "huaweicloud-sdk-go" project?

### ISSUE THREAD

**Issue by jehos** [huaweicloud/golangsdk#130]
Before starting a PR, please read the [style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md).

The "huaweicloud-sdk-go" project does not seem to be updated anymore.
However, huawei recommend using "huaweicloud-sdk-go" on the official website.
* https://support.huaweicloud.com/devg-sdk/zh-cn_topic_0089679424.html

What's different between the "huaweicloud-sdk-go" project?
Which sdk should i use?

**Comment by niuzhenguo** [comment]
@jehos Please use huaweicloud-sdk-go, golangsdk is only used for inner projects.
