### ISSUE TITLE
lb whitelist

### ISSUE THREAD

**Issue by TylerTang06** [huaweicloud/golangsdk#250]
Before starting a PR, please read the [style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md).

**Comment by TylerTang06** [comment]
lb whitelist update 不能remove白名单列表里所有Ips
"github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/lbaas_v2/whitelists"

**Comment by TylerTang06** [comment]
// UpdateOpts is the common options struct used in this package's Update
// operation.
type UpdateOpts struct {
	// EnableWhitelist *bool  `json:"enable_whitelist,omitempty"`
	// Whitelist       string `json:"whitelist,omitempty"`
	EnableWhitelist *bool  `json:"enable_whitelist"`
	Whitelist       string `json:"whitelist"`
}
需要去掉 omitempty ,Whitelist参数传入 "" 才能生效

**Comment by niuzhenguo** [comment]
@TylerTang06 这个golangsdk项目不是华为云的sdk，请去开发者网页查找官方的sdk使用，多谢！
