### ISSUE TITLE
Directory structure to follow for VPC Sub-services sdk development

### ISSUE THREAD

**Issue by Savasw** [huaweicloud/golangsdk#4]
The gophercloud repository in [gator1's repo](https://github.com/gator1/gophercloud/) has vpc module under networking folder in openstack but in huaweicloud/golangsdk repository, the vpc module is being maintained as root folder in openstack. Also the vpc module doesn't have implementation to create a VPC using sdk but it is available in gator1's repo.

Please advice the directory structure to follow and whether to merge the VPC creation code in huaweicloud/golangsdk from gator1 repository.

**Comment by freesky-edward** [comment]
@niuzhenguo I noticed that this parts of VPC was created by you, some difference of directory structure occurred between this repository and gators' there, could you please take a look at this issue?

**Comment by freesky-edward** [comment]
@Savasw I suggest to move it into this one if you think it can be done, thanks.
